name: Python application

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry (version 1.8.5)
      run: |
        python -m ensurepip
        python -m pip install --upgrade pip
        python -m pip install poetry==1.8.5
    - name: View poetry --help
      run: poetry --help

    - name: Install dependencies
      shell: bash
      run: |
        poetry add factory_boy
        poetry install

    - name: Set DJANGO_ALLOWED_HOSTS and Test
      env:
        DJANGO_ALLOWED_HOSTS: "127.0.0.1,localhost"
        SECRET_KEY: "django-insecure-1m7o0j=fme^%=59$j^!(43%wkf8ue1kfyxbq-)jylrp_#(o-t)"
      run: |
        poetry run python manage.py test
