name: Python Pull Request Workflow
on: [pull_request]

jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.11
      - name: Install poetry
        run: |
          pip install -U pip
          pip install poetry
          poetry install --with dev
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: View poetry --help
        run: poetry --help

      - name: Test
        env:
          DJANGO_ALLOWED_HOSTS: 'localhost 127.0.0.1'
          DJANGO_SETTINGS_MODULE: 'bookstore.settings'
        run: |
          poetry run python manage.py test
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}